### ISSUE TITLE
Can not install and run?

### ISSUE THREAD

**Issue by alezzigo** [kyhsa93/nestjs-rest-cqrs-example#10]
**Can not install and run**
Then install follow your Guild it's not run. Table is not exist.
I think need have automation create Schema.
Thank you!

**Comment by kyhsa93** [comment]
@alezzigo 

If you want the database to be automatically synchronized when starting this app with docker-compose up, you need to add an environment variable and use it.

You need to add DATABASE_SYNC=true to your .env or docker-compose.yml file.

After that use the docker or docker-ccompose command to recreate this app's container.

If you want to set it inside the code of this app, modify database.syncronize to be true in app.config.ts and restart the app.

Automatically synchronizing databases can lead to unintentional data loss and I think this should be prevented.

So, I think database auto-sync should be selectively enabled.

If there is any better way, please let me know.

Thank you.

**Comment by kyhsa93** [comment]
@alezzigo 

If you have more opinions on this issue, please reopen it.

Thank you.

**Comment by alezzigo** [comment]
Thank @kyhsa93 !
