### ISSUE TITLE
Drying things up?

### ISSUE THREAD

**Issue by RobertLowe** [kyhsa93/nestjs-rest-cqrs-example#14]
I noticed a lot of repetition (maybe this is just a cqrs thing), and I can understand that some is justified, but for example `closedAt` is defined 14 times across different objects/types  https://github.com/kyhsa93/nestjs-rest-cqrs-example/search?q=closedAt

So my question is this, can you think of any way to dry up your CQRS pattern?

Thanks

**Comment by kyhsa93** [comment]
@RobertLowe 
I am also very concerned about it.
I thought that it could be solved by inheriting the domain class, but it didn't work as expected.
If you have any good ideas, please help.
thank you.

**Comment by developer239** [comment]
I just wanted to write the same thing. I don't think it is necessary to re-define new interfaces every time I work with an account. For example, why would I define a new interface here when I can just use the domain model? 🤔 

https://github.com/kyhsa93/nestjs-rest-cqrs-example/blob/master/src/accounts/application/queries/account.query.ts#L1
