### ISSUE TITLE
missing manifest.yaml

### ISSUE THREAD

**Issue by kodeine** [kyhsa93/nestjs-rest-cqrs-example#15]
i was trying to deploy this to kubernetes but the yaml files are missing?

**Comment by kyhsa93** [comment]
@kodeine 
i just added manifest file. please check this out. thank you.
https://github.com/kyhsa93/nestjs-rest-cqrs-example/blob/master/manifest.yaml

**Comment by kyhsa93** [comment]
i think this issue is resolved. so i close this issue. thank you.
