### ISSUE TITLE
Where are stored events

### ISSUE THREAD

**Issue by Spoutnik97** [kyhsa93/nestjs-rest-cqrs-example#27]
Hi,
Thanks for your work, I achieved to launch it quickly.
However I don't understand how it works : 
- the both databases (redis and mysql) have the same data stored in them.
-  I don't see any event store where each event is stored to be able to come back in the past

@kyhsa93 could you help me to understand your work please?

**Comment by Kaer663** [comment]
> d, will not mark issues stale

me too
I haven't seen the redis either
